"""Structural interfaces for cross-scenario automation skills.

Uses ``typing.Protocol`` (structural subtyping) so that conforming classes
do NOT need to inherit — duck typing is sufficient.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol, runtime_checkable

from skills.android.ui_types import UIElement


@runtime_checkable
class JobSearchSkill(Protocol):
    """Methods shared by Boss and LinkedIn job-browsing skills."""

    def browse_jobs(self, keyword: str) -> bool: ...
    def get_job_list(self, xml: Optional[str] = None) -> list: ...
    def navigate_to_job(self, job: Any) -> bool: ...
    def expand_description(self, **kwargs: Any) -> bool: ...
    def get_job_detail(self, xml: Optional[str] = None) -> Dict[str, Any]: ...
    def recover_detail_page(self, **kwargs: Any) -> bool: ...
    def detect_dialog(self, xml: Optional[str] = None) -> str: ...
    def dismiss_dialog(self, dialog_type: str, **kwargs: Any) -> bool: ...
